# Required assignment 8.3 Applying the KNN method to a classification problem in Python

In [1]:
# Import the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

from module_6.study_hour.Visitor_Conversion_Case_Study import x_train

## Question 1:

Write Python code to load the Caravan data set from the provided CSV file. Display the first five rows and print basic information, including the number of rows, columns and column names.

This data set comes from the ISLR library. You can find a description of the data set here: https://cran.r-project.org/web/packages/ISLR/ISLR.pdf. Download the CSV file from this GitHub repository: https://github.com/JWarmenhoven/ISLR-python.

In [2]:
###GRADED CELL
df = pd.read_csv("data/Caravan.csv")
Number_of_rows = len(df)
Number_of_columns = len(df.columns)
Column_names = df.columns.tolist()
# YOUR CODE HERE

print("Number of rows: {Number_of_rows}",Number_of_rows)
print("Number of columns: {Number_of_columns}",Number_of_columns)
print("Column names: {Column_names}",Column_names)

Number of rows: {Number_of_rows} 5822
Number of columns: {Number_of_columns} 87
Column names: {Column_names} ['Unnamed: 0', 'MOSTYPE', 'MAANTHUI', 'MGEMOMV', 'MGEMLEEF', 'MOSHOOFD', 'MGODRK', 'MGODPR', 'MGODOV', 'MGODGE', 'MRELGE', 'MRELSA', 'MRELOV', 'MFALLEEN', 'MFGEKIND', 'MFWEKIND', 'MOPLHOOG', 'MOPLMIDD', 'MOPLLAAG', 'MBERHOOG', 'MBERZELF', 'MBERBOER', 'MBERMIDD', 'MBERARBG', 'MBERARBO', 'MSKA', 'MSKB1', 'MSKB2', 'MSKC', 'MSKD', 'MHHUUR', 'MHKOOP', 'MAUT1', 'MAUT2', 'MAUT0', 'MZFONDS', 'MZPART', 'MINKM30', 'MINK3045', 'MINK4575', 'MINK7512', 'MINK123M', 'MINKGEM', 'MKOOPKLA', 'PWAPART', 'PWABEDR', 'PWALAND', 'PPERSAUT', 'PBESAUT', 'PMOTSCO', 'PVRAAUT', 'PAANHANG', 'PTRACTOR', 'PWERKT', 'PBROM', 'PLEVEN', 'PPERSONG', 'PGEZONG', 'PWAOREG', 'PBRAND', 'PZEILPL', 'PPLEZIER', 'PFIETS', 'PINBOED', 'PBYSTAND', 'AWAPART', 'AWABEDR', 'AWALAND', 'APERSAUT', 'ABESAUT', 'AMOTSCO', 'AVRAAUT', 'AAANHANG', 'ATRACTOR', 'AWERKT', 'ABROM', 'ALEVEN', 'APERSONG', 'AGEZONG', 'AWAOREG', 'ABRAND', 'AZEILPL', 'APLEZIER', 'AFIETS', 'AINBOED', 'ABYSTAND', 'Purchase']

In [3]:
df.head(10)

,Unnamed: 0,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5,6,23,1,2,1,5,0,5,0,5,...,0,0,0,0,0,0,0,0,0,No
6,7,39,2,3,2,9,2,2,0,5,...,0,0,0,0,0,0,0,0,0,No
7,8,33,1,2,3,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
8,9,33,1,2,4,8,0,1,3,6,...,0,0,0,0,0,0,0,0,0,No
9,10,11,2,3,3,3,3,5,0,2,...,0,0,0,1,0,0,0,0,0,No

#### Obtain information on the target variable

The goal is to classify whether the `Purchase` variable is a 'yes' or a 'no', indicating whether a Caravan insurance policy was bought. This variable will be your target in the classification task. Take a moment to review its distribution before moving on.

In [4]:
df.Purchase.unique() # There are only instances of "Yes" and "No"

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [5]:
df['Purchase'].describe() # You can see that 5,474 of the 5,822 rows have "No" target -- the target is quite imbalanced.

count     5822
unique       2
top         No
freq      5474
Name: Purchase, dtype: object

## Question 2:

In the Caravan data set, the column `Purchase` indicates whether a customer made a purchase ('Yes' or 'No'). Write Python code to calculate and display the proportion of each class ('Yes' and 'No') in the `Purchase` column.

Hint: Use the `value_counts` method with the `normalize=True` parameter.

In [6]:
###GRADED CELL
ans2 = df['Purchase'].value_counts(normalize=True)
print(ans2)

Purchase
No     0.940227
Yes    0.059773
Name: proportion, dtype: float64

## Question 3:

Standardise the predictors of the data frame (the target should have 0/1 structure) and store your output to `df_scaled`. 

Hint: Use `scaler.fit_transform(df.iloc[:,:-1])`. Avoid using the `purchase` function because it generates binary output.

In [18]:
###GRADED CELL
scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df.iloc[:, :-1]), columns=df.columns[:-1])
# YOUR CODE HERE

In [20]:
df_scaled["Purchase"] = df["Purchase"].apply(lambda x: 1 if x == "Yes" else 0)

In [23]:
df

,Unnamed: 0,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,-1.731753,0.680906,-0.27258,0.406697,-1.216964,0.779405,-0.694311,0.217444,-0.068711,-0.161816,...,-0.073165,-0.081055,-0.05992,0.764971,-0.022706,-0.07365,-0.15062,-0.087348,-0.118816,0
1,-1.731158,0.992297,-0.27258,-0.859500,-1.216964,0.779405,0.302552,-0.365410,-0.068711,0.464159,...,-0.073165,-0.081055,-0.05992,0.764971,-0.022706,-0.07365,-0.15062,-0.087348,-0.118816,0
2,-1.730563,0.992297,-0.27258,-0.859500,-1.216964,0.779405,-0.694311,-0.365410,0.914172,0.464159,...,-0.073165,-0.081055,-0.05992,0.764971,-0.022706,-0.07365,-0.15062,-0.087348,-0.118816,0
3,-1.729968,-1.187437,-0.27258,0.406697,0.010755,-0.970980,1.299414,-0.948264,0.914172,0.464159,...,-0.073165,-0.081055,-0.05992,0.764971,-0.022706,-0.07365,-0.15062,-0.087348,-0.118816,0
4,-1.729373,1.225840,-0.27258,1.672893,-1.216964,1.479559,0.302552,-0.365410,-0.068711,0.464159,...,-0.073165,-0.081055,-0.05992,0.764971,-0.022706,-0.07365,-0.15062,-0.087348,-0.118816,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,1.729373,0.914449,-0.27258,-2.125697,-1.216964,0.779405,-0.694311,0.800298,-0.068711,-0.787790,...,-0.073165,-0.081055,-0.05992,0.764971,-0.022706,-0.07365,-0.15062,-0.087348,-0.118816,0
5818,1.729968,0.836602,-0.27258,1.672893,1.238473,0.779405,0.302552,-0.365410,-0.068711,0.464159,...,-0.073165,-0.081055,-0.05992,0.764971,-0.022706,-0.07365,-0.15062,-0.087348,-0.118816,0
5819,1.730563,0.680906,-0.27258,0.406697,1.238473,0.779405,-0.694311,0.800298,-1.051594,-0.161816,...,-0.073165,-0.081055,-0.05992,0.764971,-0.022706,-0.07365,-0.15062,-0.087348,-0.118816,1
5820,1.731158,0.758754,-0.27258,0.406697,-1.216964,0.779405,-0.694311,1.383152,-1.051594,-0.787790,...,-0.073165,-0.081055,-0.05992,-1.014358,-0.022706,-0.07365,-0.15062,-0.087348,-0.118816,0
5821,1.731753,0.680906,-0.27258,0.406697,0.010755,0.779405,-0.694311,0.800298,-0.068711,-0.787790,...,-0.073165,-0.081055,-0.05992,-1.014358,-0.022706,-0.07365,-0.15062,-0.087348,-0.118816,0

Technically, scaling the entire data frame at once isn’t ideal, as you’ll split the data into training and test sets later. For now, it's acceptable because the focus is simply on demonstrating how to use KNN. However, in practice, this approach introduces data leakage in which the test set influences the scaling process, which means information from the test data is indirectly used during training.

## Question 4:

Create a data frame that includes only the predictors and the target variable, and then sample 20 per cent of the data as a test set.

1. Use the `train_test_split` function from `sklearn.model_selection` to split `df_scaled` into training and testing sets, with 20 per cent reserved for testing. Assign it to `train` and `test`. 

2. From the training set, create `X_train` by dropping the `Purchase` column, and set `y_train` as the `Purchase` column.

3. Do the same for the test set: create `X_test` by dropping `Purchase`, and set `y_test` as the `Purchase` column.

In [24]:
###GRADED CELL


train, test = train_test_split(df_scaled, test_size=0.2, random_state=42)
X_train = train.drop(columns=['Purchase'])#
y_train = train['Purchase']#
X_test = test.drop(columns=['Purchase'])#
y_test = test['Purchase']#

## Question 5:

Build a KNN classifier to predict customer purchases based on the training data you have prepared.

1. Initialise a KNN classifier with $k = 1$.

2. Train the classifier using the training features `X_train` and target labels `y_train`.

3. Use the trained model to predict the target variable on the test features `X_test`.

4. Compute the confusion matrix to compare the true test labels `y_test` and the predicted labels.

In [25]:
###GRADED CELL
neigh = KNeighborsClassifier(n_neighbors=1) #train a KNN with K = 1
neigh.fit(X_train, y_train)
y_pred = neigh.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix:",cm)

Confusion matrix: [[1020   64]
 [  67   14]]

Write a function that takes a value of $k$ and returns all relevant evaluation metrics.

In [26]:
def k_stats(k, X_train, y_train, X_test, y_test):
    neigh = KNeighborsClassifier(n_neighbors=k) #train a KNN with K = 1
    neigh.fit(X_train, y_train) #fit it to our training set
    y_pred = neigh.predict(X_test) #predict the test set
    cm = confusion_matrix(y_test, y_pred)
    nr_pos = np.sum(y_pred == 1)
    true_neg = cm[0][0]
    true_pos = cm[1][1]
    false_pos = cm[0][1]
    false_neg = cm[1][0]
    misclassification_rate = (false_pos + false_neg)/np.sum(cm)
    precision = true_pos / (true_pos + false_pos) if (true_pos + false_pos) > 0 else 0.0
    sensitivity = true_pos / (true_pos + false_neg) if (true_pos + false_neg) > 0 else 0.0
    return nr_pos, true_pos, misclassification_rate, precision, sensitivity

Construct a data frame that includes the $k$ hyperparameter, and the test statistics KNN with the corresponding $k$.

In [27]:
df_knn = pd.DataFrame(columns=['K','number pos', 'true pos', 'misclassification','precision','sensitivity'])

## Question 6:

Use the `k_stats` function in a loop, and report the results obtained by the KNN method for $k = 1,3,5,7,9$.

The function `k_stats(k, X_train, y_train, X_test, y_test)`  trains a KNN classifier with $k$ neighbours and returns several evaluation metrics:

* 'nr_pos': number of positive predictions

* 'true_pos': number of true positive predictions

* 'mc': misclassification count or error

* 'pre': precision

* 'sens': sensitivity (recall)

Perform the following tasks:

1. Run a loop over five different odd values of $k$ — specifically, $k = 1, 3, 5, 7, 9$.

2. Store the results in a data frame `df_knn`.

3. Convert the columns `k`, `number pos` and `true pos` to integer type using pandas' `pd.to_numeric()` with `downcast='integer'` for memory efficiency.

In [28]:
rows = []

for k in [1, 3, 5, 7, 9]:
    nr_pos, true_pos, mc, pre, sens = k_stats(k, X_train, y_train, X_test, y_test)
    rows.append({
        "k": k,
        "number pos": nr_pos,
        "true pos": true_pos,
        "mc": mc,
        "pre": pre,
        "sens": sens,
    })

df_knn = pd.DataFrame(rows)

for col in ["k", "number pos", "true pos"]:
    df_knn[col] = pd.to_numeric(df_knn[col], downcast="integer")

In [29]:
df_knn.style.hide(axis="index")

Here, you can observe that increasing the value of $k$ leads to a higher misclassification error. However, take a look at the following:

In [30]:
y_test.value_counts(normalize = True)

Purchase
0    0.930472
1    0.069528
Name: proportion, dtype: float64

Here, you can see that even if you always predict 'No', the misclassification rate is already 6.6 per cent, so it's not surprising that the misclassification rate drops as $k$ increases. The `df_knn` shows that the larger $k$ gets, the fewer 'Yes' predictions are made. This means that misclassification should not be the main metric here. 

For example, you might consider $k = 3$, which still has an 8.2 per cent misclassification rate but correctly identifies seven positives, compared with just one positive when $k = 9$. This is a decision where managerial insights will play a role.