In [42]:
#Importing the necessary libraries
import pandas as pd
import warnings


import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [43]:
df_college = pd.read_csv('data/college_missing.csv') #Read the data

In [44]:
df_college.head()

,Unnamed: 0,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,PhD,S.F.Ratio,Grad.Rate
0,Abilene Christian University,1660.0,1232.0,721,23,52,2885,537,70,18.1,60
1,Adelphi University,2186.0,1924.0,512,16,29,2683,1227,29,12.2,56
2,Adrian College,1428.0,1097.0,336,22,50,1036,99,53,12.9,54
3,Agnes Scott College,417.0,349.0,137,60,89,510,63,92,7.7,59
4,Alaska Pacific University,NaN,146.0,55,16,44,249,869,76,11.9,15

In [45]:
df_college.isna().sum()

Unnamed: 0     0
Apps           6
Accept         7
Enroll         0
Top10perc      0
Top25perc      0
F.Undergrad    0
P.Undergrad    0
PhD            0
S.F.Ratio      0
Grad.Rate      0
dtype: int64

In [46]:
df_college[df_college['Apps'].isna()].index.tolist()

[4, 142, 279, 441, 689, 713]

In [47]:
df_college[df_college['Accept'].isna()].index.tolist()

[108, 392, 402, 445, 614, 620, 650]

In [48]:
###GRADED
df_college_dropped = df_college.copy(deep = True)
df_college_dropped_v1 = df_college_dropped.dropna()
num_of_rows = len(df_college_dropped_v1)
print("The number of rows in the original dataset is " +str(len(df_college)))


print("The number of rows in the dataset after dropping null values  is " + str(num_of_rows))

The number of rows in the original dataset is 777
The number of rows in the dataset after dropping null values  is 764

In [49]:
###GRADED
mean_of_apps = df_college['Apps'].mean()
mean_of_accepts = df_college['Accept'].mean()
median_of_accepts = df_college['Accept'].median()
median_of_apps = df_college['Apps'].median()

#Make a copy of df_college to fill in the missing data
df_college_v1 = df_college.copy(deep = True)

In [50]:
df_college_v1['Apps'] = df_college_v1['Apps'].fillna(mean_of_apps)
df_college_v1['Accept'] = df_college_v1['Accept'].fillna(mean_of_accepts)
df_college_v1

,Unnamed: 0,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,PhD,S.F.Ratio,Grad.Rate
0,Abilene Christian University,1660.000000,1232.0,721,23,52,2885,537,70,18.1,60
1,Adelphi University,2186.000000,1924.0,512,16,29,2683,1227,29,12.2,56
2,Adrian College,1428.000000,1097.0,336,22,50,1036,99,53,12.9,54
3,Agnes Scott College,417.000000,349.0,137,60,89,510,63,92,7.7,59
4,Alaska Pacific University,2985.451362,146.0,55,16,44,249,869,76,11.9,15
...,...,...,...,...,...,...,...,...,...,...,...
772,Worcester State College,2197.000000,1515.0,543,4,26,3089,2029,60,21.0,40
773,Xavier University,1959.000000,1805.0,695,24,47,2849,1107,73,13.3,83
774,Xavier University of Louisiana,2097.000000,1915.0,695,34,61,2793,166,67,14.4,49
775,Yale University,10705.000000,2453.0,1317,95,99,5217,83,96,5.8,99
776,York College of Pennsylvania,2989.000000,1855.0,691,28,63,2988,1726,75,18.1,99

In [51]:
df_college_v1.isna().sum()

Unnamed: 0     0
Apps           0
Accept         0
Enroll         0
Top10perc      0
Top25perc      0
F.Undergrad    0
P.Undergrad    0
PhD            0
S.F.Ratio      0
Grad.Rate      0
dtype: int64

In [52]:
#The Apps and Accept columns have null values
#Therefore, only those those columns are selected
#For regression, you need to separate rows with and without missing rows for training and testing data sets
#Separate rows with and without missing values in the Apps column
train_apps = df_college[df_college['Apps'].notnull()]
test_apps = df_college[df_college['Apps'].isnull()]

In [53]:
X_train_apps = train_apps[['Enroll', 'Top10perc', 'Top25perc', 'F.Undergrad', 'P.Undergrad', 'PhD', 'S.F.Ratio', 'Grad.Rate']]
y_train_apps = train_apps['Apps']

In [54]:
train_apps = df_college[df_college['Apps'].notnull()]
test_apps = df_college[df_college['Apps'].isnull()]

In [55]:
train_apps

,Unnamed: 0,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,PhD,S.F.Ratio,Grad.Rate
0,Abilene Christian University,1660.0,1232.0,721,23,52,2885,537,70,18.1,60
1,Adelphi University,2186.0,1924.0,512,16,29,2683,1227,29,12.2,56
2,Adrian College,1428.0,1097.0,336,22,50,1036,99,53,12.9,54
3,Agnes Scott College,417.0,349.0,137,60,89,510,63,92,7.7,59
5,Albertson College,587.0,479.0,158,38,62,678,41,67,9.4,55
...,...,...,...,...,...,...,...,...,...,...,...
772,Worcester State College,2197.0,1515.0,543,4,26,3089,2029,60,21.0,40
773,Xavier University,1959.0,1805.0,695,24,47,2849,1107,73,13.3,83
774,Xavier University of Louisiana,2097.0,1915.0,695,34,61,2793,166,67,14.4,49
775,Yale University,10705.0,2453.0,1317,95,99,5217,83,96,5.8,99
776,York College of Pennsylvania,2989.0,1855.0,691,28,63,2988,1726,75,18.1,99

In [56]:
test_apps

,Unnamed: 0,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,PhD,S.F.Ratio,Grad.Rate
4,Alaska Pacific University,NaN,146.0,55,16,44,249,869,76,11.9,15
142,Columbia College MO,NaN,158.0,132,10,28,690,5346,87,15.3,37
279,James Madison University,NaN,5285.0,2082,32,72,9652,742,77,17.9,98
441,Pacific Lutheran University,NaN,1392.0,504,31,68,2580,302,78,11.0,83
689,University of the South,NaN,966.0,326,46,83,1129,24,89,10.3,82
713,Virginia Tech,NaN,11719.0,4277,29,53,18511,604,85,13.8,73

In [57]:
#Define the predictors and target
X_train_apps = train_apps[['Enroll', 'Top10perc', 'Top25perc', 'F.Undergrad', 'P.Undergrad', 'PhD', 'S.F.Ratio', 'Grad.Rate']]
y_train_apps = train_apps['Apps']

In [58]:
model_apps = LinearRegression()
model_apps.fit(X_train_apps, y_train_apps)

LinearRegression()

In [59]:
#Predict the missing Apps values
X_test_apps = test_apps[['Enroll', 'Top10perc', 'Top25perc', 'F.Undergrad', 'P.Undergrad', 'PhD', 'S.F.Ratio', 'Grad.Rate']]
predicted_apps = model_apps.predict(X_test_apps)

In [60]:
#Replace the missing Apps values with predictions
df_college.loc[df_college['Apps'].isnull(), 'Apps'] = predicted_apps